version: '3.7'
services:
  frontend:
    container_name: frontend
    image: keenan218/sfia2-project:frontend
    build: ./frontend
    depends_on:
      - backend
    
  backend:
    container_name: backend
    image: keenan218/sfia2-project:backend
    build: ./backend
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=database
      - DATABASE_URI=${DB_URI}
      - TEST_DB_URI=${TEST_DB_URI}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mysql

  mysql:
    # tty: true
    container_name: database
    image: keenan218/sfia2-project:database
    build: ./database
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      
  nginx:
    image: keenan218/sfia2-project:nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend


