version: '3.7'
services:
  frontend:
    image: frontend #:latest
    build: ./frontend
    depends_on:
      - backend
    
  backend:
    image: backend #:latest
    build: ./backend
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=database
      - DATABASE_URI=mysql+pymysql://root:password@mysql:3306/users
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mysql

  mysql:
    # tty: true
    image: database #:latest
    build: ./database
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend