version: '3.5'
services:
  frontend:
    image: frontend:latest
    build: ./frontend
    
  backend:
    image: backend:latest
    build: ./backend
    environment: 
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
      - MYSQL_DATABASE=database
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - database
      
  database:
    image: database:latest
    build: ./database
    environment: 
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
      
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
