apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: keenan218/backend:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: DB_PASSWORD
              value: password
            - name: TEST_DATABASE_URI
              value: mysql+pymysql://root:password@test-db.csnk6wgrqbvm.eu-west-2.rds.amazonaws.com:3306/testdb
            - name: DATABASE_URI
              value: mysql+pymysql://root:password@prod-db.csnk6wgrqbvm.eu-west-2.rds.amazonaws.com:3306/users
            - name: SECRET_KEY
              value: mine
            - name : MYSQL_DATABASE
              value: mysql
          ports:
            - containerPort: 5001

